### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by MikolajDuda** [koboskom/person_recognition#1]
1. W systemie linux nie działa otwieranie plików z logami z poziomu programu - powodem jest brak programu notepad.exe w linuxie.
![issue_1](https://user-images.githubusercontent.com/44867907/104052498-1ca98180-51ea-11eb-9ad4-b688985f4b97.png)

2. Możliwość wyboru pliku niebędącego plikiem wideo w obsługiwanym formacie, co może prowadzić do nieprzewidzianych wyników i błędów. Sugerujemy aby ta opcja była zablokowana lub po wybraniu niepoprawnego formatu wyświetlany był błąd.
![issue_2](https://user-images.githubusercontent.com/44867907/104053125-018b4180-51eb-11eb-983a-22329ac2303d.png)

3. Próba uruchomienia programu z pythonem w wersji 3.9.x kończy się niepowodzeniem. Dzieje się tak, ponieważ tensorflow działa tylko do wersji 3.8.x. Proponujemy, aby dopisać w README wymaganie odnośnie odpowiedniej wersji pythona.

4. Przy instalacji requirements pipem występuje błąd związany z wersją opencv-python, która nie jest znajdowana. Po instalacji opencv-python bez konkretnej wersji program działa.

**Comment by koboskom** [comment]
3. błąd naprawiony, zaktualizowano readme
4. błąd naprawiony, zaktualizowano readme

**Comment by koboskom** [comment]
1. błąd naprawiony, zaktualizowano readme

**Comment by koboskom** [comment]
2. błąd naprawiony, nie da się już wybrać pliku innego niż wideo z poziomu file explorera

**Comment by MikolajDuda** [comment]
Dziękujemy za współpracę, potwierdzamy naprawienie błędów.
